[TC-6712] - update attach documents docs
tradecloud/tradecloud-docs-api-v2 pull request #17
Opened 2021-01-29 11:34 UTC by olegtradecloud

## Description

https://tradecloud.atlassian.net/browse/TC-6712

### Scope
This PR updates attach documents docs

### Submitter pre-flight check

- [x] Review your documentation
- [x] Add labels `needs reviewing`
- [x] Assign PR and JIRA ticket to 'Reviewer' (in 'Reviewing' state)

### Reviewer pre-flight check

- [ ] Review documentation in PR
- [ ] Remove label `needs reviewing`
- [ ] Merge the PR and remove the release for this branch from Gitbook
- [ ] Set Jira ticket to 'Released'

2021-01-30 17:04 UTC, marcmatt requested changes
Looks good, some improvements needed.
- Also add to "Issue a new order" -> "Lines" -> "Other line fields":
"documents: contain attached documents, see:"
And then the link to /buyer/issue/attach-document
- This has already been done for "Other order fields"
  change "contain meta data and link of attached documents" to "documents: contain attached documents, see:"

2021-01-30 17:04 UTC, marcmatt commented on buyer/issue/attach-document.md
> +### Step 2. Choose an appropriate url to attach the document
appropriate API (3x)

2021-02-01 10:18 UTC, olegtradecloud commented on buyer/issue/attach-document.md
> +### Step 2. Choose an appropriate url to attach the document
Fixed

2021-02-01 10:18 UTC, olegtradecloud commented on buyer/issue/attach-document-url.md
> +Body example:
Fixed

2021-02-01 10:19 UTC, olegtradecloud commented on buyer/issue/attach-document-url.md
> +You can attach documents using either of the following urls
Fixed

2021-02-01 10:19 UTC, olegtradecloud commented on buyer/issue/attach-document-url.md
> +## 1. Attach documents using the /order/documents API
Fixed

2021-02-01 10:21 UTC, olegtradecloud commented on buyer/issue/attach-document-url.md
> +description: Choose an appropriate url to attach a document to an order or line
Fixed

2021-02-01 10:21 UTC, olegtradecloud commented on SUMMARY.md
> +    * [Choose attach document URL](buyer/issue/attach-document-url.md)
Fixed

2021-02-01 10:54 UTC, olegtradecloud commented on buyer/issue/attach-document-url.md
> +Body example:
@marcmatt It was supposed to be an example of `/order`  body, but without additional fields

2021-02-01 13:27 UTC, marcmatt approved these changes
Looks great!

2021-02-01 13:27 UTC, merged